apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit
  template:
    metadata:
      labels:
        app: qbit
    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000
        runAsGroup: 1000
      strategy:
        type: Recreate 
      selector:
        matchLabels:
          app: qbit
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add: 
              - NET_ADMIN
              - NET_RAW
        env:
        - name: DOT
          value: "off"
        - name: HEALTH_WAIT_DURATION
          value: "60s" 
        - name: VPN_PORT_FORWARDING
          value: "on"
        - name: VPN_PORT_FORWARDING_UP_COMMAND
          value: >-
            /bin/sh -c '
            sleep 5;
            PORT=$(cat /tmp/gluetun/forwarded_port);
            wget --post-data="json={\"listen_port\":$PORT}" http://localhost:8080/api/v2/app/setPreferences;
            '
        - name: HEALTH_TARGET_ADDRESS
          value: "1.1.1.1:443"
        - name: WIREGUARD_MTU
          value: "1280"
        - name: VPN_SERVICE_PROVIDER
          value: "protonvpn"
        - name: VPN_TYPE
          value: "wireguard"
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: vpn-creds
              key: wireguard_private_key
        - name: SERVER_COUNTRIES
          value: "Netherlands"
        ports:
        - containerPort: 8080 
          name: http
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-device
      - name: qbit
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: WEBUI_PORT
          value: "8080"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbit-config
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
      - name: tun-device
        hostPath:
          path: /dev/net/tun
