apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-creds
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store
    kind: ClusterSecretStore
  target:
    name: vpn-creds
  data:
  - secretKey: wireguard_private_key
    remoteRef:
      key: fe6d787c-f573-4ab1-8021-b42c00999751
