apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        resources:
        requests:
          gpu.intel.com/i915: "1"
        limits:
          gpu.intel.com/i915: "1"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
          - containerPort: 8096
        volumeMounts:
        - name: config-storage
          mountPath: /config
        - name: media-storage
          mountPath: /media
      volumes:
      - name: config-storage
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: media-storage
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
  syncPolicy:
    automated:              
      prune: true          
      selfHeal: true       
    syncOptions:
      - CreateNamespace=true 
