apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smbcreds-external
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store
    kind: ClusterSecretStore
  target:
    name: smbcreds
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: 23519f00-e3c3-4998-b1b8-b42300fa25b3
  - secretKey: password
    remoteRef:
      key: b096fe51-55b6-4253-bee1-b42300f8c8f4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes: [ "ReadWriteMany" ]
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm 
    - rw
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media-unique-id
    volumeAttributes:
      source: "//192.168.0.82/jellyfin"
    nodeStageSecretRef:
      name: smbcreds
      namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: ""
  volumeName: jellyfin-media-pv
  resources:
    requests:
      storage: 10Ti