project: default
source:
  repoURL: https://charts.longhorn.io/
  targetRevision: 1.11.1
  helm:
    parameters:
      - name: defaultSettings.defaultReplicaCount
        value: '3'
    values: |
      preUpgradeChecker:
        jobEnabled: false
      ingress:
        enabled: true
        host: longhorn.lab
        ingressClassName: traefik
  chart: longhorn
destination:
  server: https://kubernetes.default.svc
  namespace: longhorn-system
syncPolicy:
  syncOptions:
    - CreateNamespace=true
