apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: media
stringData:
  username: "media_server"
  password: "7tQsSH8V^f&^C&"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes: [ "ReadWriteMany" ]
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media-unique-id
    volumeAttributes:
      source: "//192.168.0.82/jellyfin"
    nodeStageSecretRef:
      name: smbcreds
      namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: ""
  volumeName: jellyfin-media-pv
  resources:
    requests:
      storage: 10Ti