apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-store
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            name: bw-auth-token
            namespace: external-secrets
            key: token
