apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-store
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: "https://cluster.local"
      organizationID: "59a537ca-989e-4bad-b638-b42300f808ce"
      projectID: "c7da6680-13b0-4c0d-8f12-b42300f83e0e"
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
        namespace: external-secrets
      auth:
        secretRef:
          credentials:
            name: bw-auth-token
            namespace: external-secrets
            key: token
